const SET_CURRENT_USER = 'SET_CURRENT_USER';
const SET_NOTES_COLLECTION = 'SET_NOTES_COLLECTION';
const SET_APP_FONT = 'SET_APP_FONT';

export { 
  SET_CURRENT_USER, 
  SET_NOTES_COLLECTION, 
  SET_APP_FONT
};
